### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ledjon-behluli** [Surveily/Orleans.Streaming.Grains#6]
Does this package allow for Fan-Out i.e: multiple consumers can read the same stream message?
Thanks

**Comment by turowicz** [comment]
Yes its a typical stream provider. It has all the same features.

**Comment by turowicz** [comment]
Also have a look here: https://github.com/Surveily/Orleans.Streaming.Grains/tree/main/src/Orleans.Streaming.Grains.Tests/Streams/Grains
